spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:tracetable_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin_pass}
  jpa:
    hibernate:
      ddl-auto: update